server:
  port: 8088
  session-timeout: 60
spring:
  servlet:
     multipart: 
        max-file-size: 10MB
        max-request-size: 10MB
  ## quartz定时任务,采用数据库方式
  ##quartz:
    ##job-store-type: jdbc
  #json 时间戳统一转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  aop:
    proxy-target-class: true
  mvc:
    static-path-pattern: /**
  resource:
    static-locations: classpath:/static/,classpath:/public/
  datasource:
    url: jdbc:oracle:thin:@172.16.221.96:1521:orcl
    username: hcjg
    password: hcjg
    driver-class-name: oracle.jdbc.driver.OracleDriver
    max-active: 100 
    max-wait: 10000
    max-idle: 10
    min-idle: 5
  jpa:  
    hibernate:  
      ddl-auto: none  
    show-sql: true  
# mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config: 
    db-config:
      db-type: oracle
      id-type: 2
      auto-set-db-type: true
      db-column-underline: true
      map-underscore-to-camel-case: true
    configuration:
      jdbc-type-for-null: null
      # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
