server:
  port: 8088
  session-timeout: 60
# 定义调度时间
schedule:
  time: 6000
  
spring:
  servlet:
     multipart: 
        max-file-size: 10MB
        max-request-size: 10MB
  ## quartz定时任务,采用数据库方式
  ##quartz:
    ##job-store-type: jdbc
  #json 时间戳统一转换
  jackson:
    #设置空如何序列化
    #defaultPropertyInclusion: NON_NULL
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  aop:
    proxy-target-class: true
  mvc:
    static-path-pattern: /**
  resource:
    static-locations: classpath:/static/,classpath:/public/
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@47.105.215.180:1521:orcl
    username: c##hanlm
    password: hanlm
    driver-class-name: oracle.jdbc.driver.OracleDriver
    # 连接池启动时的初始值.
    initial-size: 50
    # 连接池的最大值.
    max-active: 1500
    # 配置获取连接等待超时的时间.
    max-wait: 1000
    # 最大空闲值.当经过一个高峰时间后，连接池可以慢慢将已经用不到的连接慢慢释放一部分，一直减少到maxIdle为止.
    # max-idle: 10
    # 最小空闲值.当空闲的连接数少于阀值时，连接池就会预申请去一些连接，以免洪峰来时来不及申请.
    min-idle: 5
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 1 from dual
    testOnBorrow: false
    testWhileIdle: true
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    logAbandoned: true
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxOpenPreparedStatements: 100
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:  
    hibernate:  
      ddl-auto: none  
    show-sql: true  
# mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config: 
    banner: false
    db-config:
      db-type: oracle
      id-type: 2
      auto-set-db-type: true
      db-column-underline: true
      map-underscore-to-camel-case: true
    configuration:
      jdbc-type-for-null: null
      # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      # 实体扫描，多个package用逗号或者分号分隔
      type-aliases-package: com.hanlm.**.entity

